kind: pipeline
type: docker
name: Testing Python CI/CD


steps:
- name: Black Code Format Check
  image: aoluwatosin10/netauto
  commands:
  - black . --check

- name: Precheck OSPF and BGP
  image: aoluwatosin10/netauto
  commands:
  - python3 test.py --disable-pytest-warnings -s

- name: Deploy Configurations
  image: aoluwatosin10/netauto
  environment:
    MY_SECRET:
      from_secret: MY_SECRET
  commands:
  - python build.py --no_dry_run
  when:
    branch:
    - master
    - main

trigger:
  event:
    exclude:
    - pull_request
- name: Suzieq Check
  image: python:3.8
  commands:
  - pip install suzieq rich
  - python3 test_suzieq.py
  when:
    branch:
    - master
    - main
  volumes:
  - name: suzieq
    path: /tmp/suz

volumes:
- name: suzieq
  host:
    path: /home/neteng/suz
