kind: pipeline
type: docker
name: Testing Python CI/CD


steps:
- name: Black Code Format Check
  image: aoluwatosin10/netauto
  commands:
  - black . --check

- name: Batfish Prechecks
  image: aoluwatosin10/netauto
  commands:
  - python test.py

- name: Precheck Configuration Diff
  image: aoluwatosin10/netauto
  environment:
    MY_SECRET:
      from_secret: MY_SECRET
  commands:
  - python build.py --dry_run

- name: Deploy Configurations
  image: aoluwatosin10/netauto
  environment:
    MY_SECRET:
      from_secret: MY_SECRET
  commands:
  - python build.py --no_dry_run
  when:
    branch:
    - master
    - main

- name: Suzieq Check
  image: python:3.8
  commands:
  - pip install suzieq rich
  - python test_suzieq.py
  when:
    branch:
    - master
    - main
  volumes:
  - name: suzieq
    path: /tmp/suz

volumes:
- name: suzieq
  host:
    path: /home/neteng/suz

trigger:
  event:
    exclude:
    - pull_request
