---
pdx-rtr-eos-01:
  hostname: 192.168.7.49
  groups:
    - eos

pdx-rtr-eos-02:
  hostname: 192.168.7.48
  groups:
    - eos

pdx-rtr-eos-03:
  hostname: 192.168.7.50
  groups:
    - eos

pdx-rtr-eos-04:
  hostname: 192.168.7.47
  groups:
    - eos
